-- MySQL Script generated by MySQL Workbench
-- Sun Feb 24 15:51:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lumato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lumato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lumato` DEFAULT CHARACTER SET utf8 ;
USE `lumato` ;

-- -----------------------------------------------------
-- Table `lumato`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumato`.`users` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lumato`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumato`.`cars` (
  `idcars` INT(11) NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NULL DEFAULT NULL,
  `brand` VARCHAR(45) NULL DEFAULT NULL,
  `year` INT(11) NULL DEFAULT NULL,
  `iduser` INT(11) NOT NULL,
  `fuelType` VARCHAR(45) NULL DEFAULT NULL,
  `comment` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcars`),
  INDEX `fk_cars_users_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_cars_users`
    FOREIGN KEY (`iduser`)
    REFERENCES `lumato`.`users` (`iduser`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lumato`.`extracosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumato`.`extracosts` (
  `idextraCosts` INT(11) NOT NULL AUTO_INCREMENT,
  `cost` DECIMAL(7,2) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `idcars` INT(11) NOT NULL,
  PRIMARY KEY (`idextraCosts`, `idcars`),
  INDEX `fk_extraCosts_cars1_idx` (`idcars` ASC) VISIBLE,
  CONSTRAINT `fk_extraCosts_cars1`
    FOREIGN KEY (`idcars`)
    REFERENCES `lumato`.`cars` (`idcars`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lumato`.`fuelcosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumato`.`fuelcosts` (
  `idfuelcost` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `priceperliter` DECIMAL(4,2) NULL DEFAULT NULL,
  `amountoffuel` DECIMAL(4,1) NULL DEFAULT NULL,
  `currentmileage` INT(11) NULL DEFAULT NULL,
  `typeoffuel` VARCHAR(45) NULL DEFAULT NULL,
  `idcar` INT(11) NOT NULL,
  PRIMARY KEY (`idfuelcost`),
  INDEX `fk_fuelCosts_cars1_idx` (`idcar` ASC) VISIBLE,
  CONSTRAINT `fk_fuelCosts_cars1`
    FOREIGN KEY (`idcar`)
    REFERENCES `lumato`.`cars` (`idcars`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
